### ISSUE TITLE
No display of getin throw in local siteswap

### ISSUE THREAD

**Issue by j-c-stuifbergen** [namlit/siteswap_generator#57] opened 2023-08-18 10:33 UTC
![Screenshot_20230818-121929](https://github.com/namlit/siteswap_generator/assets/10435015/79f8d641-cf94-400d-910e-3bb1b53d33b3)

But here, the getin-throw is not included:
![Screenshot_20230818-122909](https://github.com/namlit/siteswap_generator/assets/10435015/7dbcbe19-585d-4452-a2f1-f8f53d7b05c7)

(Screenshots from an Android phone)

**Comment by namlit** [comment] 2023-09-03 22:40
Hi, sorry for the late response.

That is actually by design. On the top where the global siteswap is shown, the app always shows all getin throws needed to get into the pattern from ground state. In the local view the app tries to avoid getin throws, which are not strictly necessary by distributing the clubs accordingly. As you can see in the second screenshot juggler A has only two clubs and jugger B has four clubs. This is just to avoid getin throws. If you would start with the ground state club distribution, where every jugger has two clubs in the right hand and one club in the left hand, you would need to throw the getin throws printed in the global siteswap.

Also in the first screenshot only two necessary getins are shown. The other four getins are handled by the club distribution (empty left hand for jugger A, four clubs for juggler B, 2 clubs in the left hand for juggler C).

Generally a getin throw needs to be actually thrown, if a regular throw lands before the getin in the same hand as the getin throw. Otherwise you would need to catch a club in a non-empty hand. If that is not the case you can just assume the getin throw already happened and put the club into the hand where the getin throw would have landed right from the start.

Lets e.g. have a look at the 2-person pattern 972. If you wanted to start that pattern with the zip the pattern with all getins would be <7788>297 (numbers in <> are getins)

```
Beat:                  1  2  3  4  5  6  7  8  9  10 11 12
Getin Catches A:                               7     8    
Regular Catches A:                       2                                  
                       R     L     R     L     R     L
Juggler A Throws:     <7     8     2     7     9     2      
Juggler B Throws:         7     8>    9     2     7     9
                          R     L     R     L     R     L
Regular Catches B:                                2       
Getin Catches B:                            7           8
```

As you can see the first regular catch would be the zip from juggler A on beat 7 in the left hand. The third getin throw also lands in the left hand of juggler A on beat 11. So the first 8 definitely has to be thrown, otherwise juggler A would not have an empty hand for the zip. The second 8 is just thrown, because it is after the first 8. The first two getin throws however can be omitted by giving juggler B 2 clubs into the left hand instead of the right hand.

In your first sceenshot the same thing applies. You have the pattern <aaaabb>9bb3b. The first b from the getins lands in the same hand as the first zip, so it needs to be throws to have an empty hand for the zip. Thus the app shows the first b from the getins (and all following getins) in the local view.

By the way, while looking at the 972 example I might have discovered a bug. If you start 972 with the 7 I see no reason, why that should not be possible to do without necessary getin throws, the app however tells me to throw a 9 as getin. I need to investigate that. I will create a separate ticket.

**Closed by namlit** 2023-09-03 22:40 UTC

**Comment by j-c-stuifbergen** [comment] 2023-09-04 14:07
Thanks for the explanation!
I think that it would be good to explain in the app that the global  may show more getin throws than the local siteswap.

**Comment by namlit** [comment] 2023-09-04 22:30
Good point, I will create a ticket. I thought I already had an explanation in the App, but apparently I do not.
